解决用户直接使用扫码方式登陆的hotReloadStorage的nil问题
eatmoreapple/openwechat pull request #268
Opened 2023-02-09 13:37 UTC by wenyoufu

2023-02-10 01:38 UTC, eatmoreapple requested changes

2023-02-17 01:34 UTC, wenyoufu commented on bot.go
> +			}
嗯，对的；这块不要返回err

2023-02-17 01:47 UTC, wenyoufu commented on bot.go
> -func (b *Bot) DumpTo(writer io.Writer) error {
> DumpTo 肯定需要的，保留自由度让用户主动导出到别的地方。
这个导出接口针对上层用户并没有实际价值；从系统层面来讲，只是保留了openwechat的信息供内部使用；我的建议是去除冗余

2023-02-17 01:48 UTC, wenyoufu commented on bot.go
> -			_ = b.DumpHotReloadStorage()
> 导出即使失败了也不影响消息处理逻辑，所以这个错误暂时忽略了。

这块还是处理一下，至少有打印日志留存较好，也比较容易线上定位

2023-02-23 07:52 UTC, closed without merging