FIX:兼容go1.18
eatmoreapple/openwechat pull request #473
Opened 2024-04-11 02:42 UTC by Yonsun-w

2024-04-11 02:43 UTC, Yonsun-w commented
q

2024-04-11 13:57 UTC, dyxs-site commented
## 我觉得有很有必要兼容go1.18版本
 今天使用 `vercel` 来构建项目的时候总是失败，经过排查才发现是 `go 1.20` 太高了
由于最近开发的项目依赖于 `vercel` 搭建 而 `vercel` 的 `go` 版本 `Downloading go: https://dl.google.com/go/go1.18.10.linux-amd64.tar.gz` 太低了，这个改不动，希望这个早点 `merge` 进来
![image](https://github.com/eatmoreapple/openwechat/assets/156647601/6a31e6ae-2660-4a2b-80de-0d5690c5f382)
![image](https://github.com/eatmoreapple/openwechat/assets/156647601/3189cc63-8bec-4f0f-a5d9-b75250be981e)
![image](https://github.com/eatmoreapple/openwechat/assets/156647601/4f140a66-f196-4b5a-963e-719f76000835)
![image](https://github.com/eatmoreapple/openwechat/assets/156647601/58d5ad9f-ea55-4c11-af29-e28a82ec2aa7)

2024-04-11 14:46 UTC, Yonsun-w commented
> ## 我觉得有很有必要兼容go1.18版本
> * 今天使用 `vercel` 来构建项目的时候总是失败，经过排查才发现是 `go 1.20` 太高了
> * 由于最近开发的项目依赖于 `vercel` 搭建 而 `vercel` 的 `go` 版本 `Downloading go: https://dl.google.com/go/go1.18.10.linux-amd64.tar.gz` 太低了，系统自带的版本这个改不动，希望这个早点 `merge` 进来
> 
> ![image](https://private-user-images.githubusercontent.com/156647601/321655189-6a31e6ae-2660-4a2b-80de-0d5690c5f382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDcwMDgsIm5iZiI6MTcxMjg0NjcwOCwicGF0aCI6Ii8xNTY2NDc2MDEvMzIxNjU1MTg5LTZhMzFlNmFlLTI2NjAtNGEyYi04MGRlLTBkNTY5MGM1ZjM4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNDQ1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGNjYjg3NDYwZDFmZjE4ZGU4ZGY3N2IyNDc3N2Y5ZDUyNDViYzQzODMxN2E3MzBmMWMwMmUyNjcwNWNlMDBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._htavzKmNsA6pxKIqn0FtZ9psTcf8JRvuV06gfHfr04) ![image](https://private-user-images.githubusercontent.com/156647601/321655360-3189cc63-8bec-4f0f-a5d9-b75250be981e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDcwMDgsIm5iZiI6MTcxMjg0NjcwOCwicGF0aCI6Ii8xNTY2NDc2MDEvMzIxNjU1MzYwLTMxODljYzYzLThiZWMtNGYwZi1hNWQ5LWI3NTI1MGJlOTgxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNDQ1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODVhYjY3NzIwZTFmOWY0ZmZmY2EwZWY2Y2NiOGFkY2Y4YjEzYjc1M2YyNzZkYTNkZTU1OThmNWU1ZTZhNzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YD_wlffrjUozLuCGKwkBUJgI_3XtXIjlB-ngKelgyU4) ![image](https://private-user-images.githubusercontent.com/156647601/321655549-4f140a66-f196-4b5a-963e-719f76000835.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDcwMDgsIm5iZiI6MTcxMjg0NjcwOCwicGF0aCI6Ii8xNTY2NDc2MDEvMzIxNjU1NTQ5LTRmMTQwYTY2LWYxOTYtNGI1YS05NjNlLTcxOWY3NjAwMDgzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNDQ1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjhlZmVmOTFlN2Y2ODA3MjA3MWMzODg3OGFiMGJjN2VlZWFhYmMyZWZjOWU2NjM3NzkxNTBhMTU1YjZmYzFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wn5nn4SujFyiXXAzdQbwaznlc2vRfc0pt6xLX77h3Zo) ![image](https://private-user-images.githubusercontent.com/156647601/321655853-58d5ad9f-ea55-4c11-af29-e28a82ec2aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDcwMDgsIm5iZiI6MTcxMjg0NjcwOCwicGF0aCI6Ii8xNTY2NDc2MDEvMzIxNjU1ODUzLTU4ZDVhZDlmLWVhNTUtNGMxMS1hZjI5LWUyOGE4MmVjMmFhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNDQ1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTMxNmY4MzYyYzA2MzMwN2RmZDAxMDllOWE1ODE0ZDU5MTFhZjM2ZDNlYjEzZjYzZjE5MzNmYjY5YTdkNTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2ahCLJWhetDOG5NPRzuqSiLOeUpF4lii8GPwunvz1sk)

您好，可以先用我的
go get -u github.com/Yonsun-w/openwechat

2024-04-12 01:56 UTC, dyxs-site commented
> > ## 我觉得有很有必要兼容go1.18版本
> > 
> > * 今天使用 `vercel` 来构建项目的时候总是失败，经过排查才发现是 `go 1.20` 太高了
> > * 由于最近开发的项目依赖于 `vercel` 搭建 而 `vercel` 的 `go` 版本 `Downloading go: https://dl.google.com/go/go1.18.10.linux-amd64.tar.gz` 太低了，系统自带的版本这个改不动，希望这个早点 `merge` 进来
> > 
> > ![image](https://private-user-images.githubusercontent.com/156647601/321655189-6a31e6ae-2660-4a2b-80de-0d5690c5f382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDcwMDgsIm5iZiI6MTcxMjg0NjcwOCwicGF0aCI6Ii8xNTY2NDc2MDEvMzIxNjU1MTg5LTZhMzFlNmFlLTI2NjAtNGEyYi04MGRlLTBkNTY5MGM1ZjM4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNDQ1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGNjYjg3NDYwZDFmZjE4ZGU4ZGY3N2IyNDc3N2Y5ZDUyNDViYzQzODMxN2E3MzBmMWMwMmUyNjcwNWNlMDBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._htavzKmNsA6pxKIqn0FtZ9psTcf8JRvuV06gfHfr04) ![image](https://private-user-images.githubusercontent.com/156647601/321655360-3189cc63-8bec-4f0f-a5d9-b75250be981e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDcwMDgsIm5iZiI6MTcxMjg0NjcwOCwicGF0aCI6Ii8xNTY2NDc2MDEvMzIxNjU1MzYwLTMxODljYzYzLThiZWMtNGYwZi1hNWQ5LWI3NTI1MGJlOTgxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNDQ1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODVhYjY3NzIwZTFmOWY0ZmZmY2EwZWY2Y2NiOGFkY2Y4YjEzYjc1M2YyNzZkYTNkZTU1OThmNWU1ZTZhNzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YD_wlffrjUozLuCGKwkBUJgI_3XtXIjlB-ngKelgyU4) ![image](https://private-user-images.githubusercontent.com/156647601/321655549-4f140a66-f196-4b5a-963e-719f76000835.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDcwMDgsIm5iZiI6MTcxMjg0NjcwOCwicGF0aCI6Ii8xNTY2NDc2MDEvMzIxNjU1NTQ5LTRmMTQwYTY2LWYxOTYtNGI1YS05NjNlLTcxOWY3NjAwMDgzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNDQ1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjhlZmVmOTFlN2Y2ODA3MjA3MWMzODg3OGFiMGJjN2VlZWFhYmMyZWZjOWU2NjM3NzkxNTBhMTU1YjZmYzFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wn5nn4SujFyiXXAzdQbwaznlc2vRfc0pt6xLX77h3Zo) ![image](https://private-user-images.githubusercontent.com/156647601/321655853-58d5ad9f-ea55-4c11-af29-e28a82ec2aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDcwMDgsIm5iZiI6MTcxMjg0NjcwOCwicGF0aCI6Ii8xNTY2NDc2MDEvMzIxNjU1ODUzLTU4ZDVhZDlmLWVhNTUtNGMxMS1hZjI5LWUyOGE4MmVjMmFhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNDQ1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTMxNmY4MzYyYzA2MzMwN2RmZDAxMDllOWE1ODE0ZDU5MTFhZjM2ZDNlYjEzZjYzZjE5MzNmYjY5YTdkNTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2ahCLJWhetDOG5NPRzuqSiLOeUpF4lii8GPwunvz1sk)
> 
> 您好，可以先用我的 go get -u github.com/Yonsun-w/openwechat

## 可以了，Yea!

![image](https://github.com/eatmoreapple/openwechat/assets/156647601/a2833f64-0f7b-4de8-b89e-c50844cc4b21)

2024-04-18 01:47 UTC, eatmoreapple requested changes
这样它不兼容errors.Is的

2024-05-16 03:20 UTC, closed without merging